// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelToBackend.Data;

#nullable disable

namespace TravelToBackend.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241012045340_Daviwyot")]
    partial class Daviwyot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelToBackend.Models.Company", b =>
                {
                    b.Property<int>("Company_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Company_Id");

                    b.ToTable("Companiebi");

                    b.HasData(
                        new
                        {
                            Company_Id = 1,
                            Name = "TBCKVADRO",
                            description = "saswauli kompania romelic arasdros iarsebs",
                            img_name = "tbc_image.png",
                            owner = "gela"
                        },
                        new
                        {
                            Company_Id = 2,
                            Name = "liberti",
                            description = "raxdeba sh",
                            img_name = "liberti_img.png",
                            owner = "NEKA"
                        },
                        new
                        {
                            Company_Id = 3,
                            Name = "bog",
                            description = "imedia",
                            img_name = "bog_image.png",
                            owner = "NAK"
                        },
                        new
                        {
                            Company_Id = 4,
                            Name = "kripto",
                            description = "iarsebs",
                            img_name = "credit_bank.png",
                            owner = "bark"
                        });
                });

            modelBuilder.Entity("TravelToBackend.Models.Turebi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Company_Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("image_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Company_Id");

                    b.ToTable("Turebi");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Company_Id = 1,
                            Description = "aq iyo batoni wyali romelmac wyali dalia",
                            Name = "Antarqtida",
                            Price = 5.9900000000000002,
                            image_name = "31394_1.jpg"
                        },
                        new
                        {
                            id = 2,
                            Company_Id = 3,
                            Description = "tbilo tibifli",
                            Name = "Tbilisi",
                            Price = 15.99,
                            image_name = "59564_1.jpg"
                        },
                        new
                        {
                            id = 3,
                            Company_Id = 2,
                            Description = "parizelta dedaqali",
                            Name = "Parizi",
                            Price = 6.9900000000000002,
                            image_name = "59564_1.jpg"
                        },
                        new
                        {
                            id = 4,
                            Company_Id = 4,
                            Description = "მაგარიი პონტიიი",
                            Name = "Los-Angeles, CA",
                            Price = 15555.0,
                            image_name = "ee2aa1e4-37d6-41e1-a3b5-ee7d35f0202d.jfif"
                        },
                        new
                        {
                            id = 5,
                            Company_Id = 1,
                            Description = "მაგარიი პონტიიი",
                            Name = "Italy",
                            Price = 12341.0,
                            image_name = "bffe2b9f-956c-41a5-a72e-12b08c899a45.jfif"
                        },
                        new
                        {
                            id = 6,
                            Company_Id = 2,
                            Description = "მაგარიი პონტიიი",
                            Name = "Brazil",
                            Price = 15111.0,
                            image_name = "b373e51c-0ba1-4f3b-887d-3499cb200d3c.jpg"
                        },
                        new
                        {
                            id = 7,
                            Company_Id = 4,
                            Description = "მაგარიი პონტიიი",
                            Name = "Denmark",
                            Price = 19000.0,
                            image_name = "f521cee9-6c84-4a02-8f75-9800f0002a53.jfif"
                        },
                        new
                        {
                            id = 8,
                            Company_Id = 3,
                            Description = "მაგარიი პონტიიი",
                            Name = "Spain",
                            Price = 23000.0,
                            image_name = "6d4ea991-f9a5-4ec6-8550-0e4e02e5ab4c.jfif"
                        });
                });

            modelBuilder.Entity("TravelToBackend.Models.Turebi", b =>
                {
                    b.HasOne("TravelToBackend.Models.Company", "Company")
                        .WithMany("Turebi")
                        .HasForeignKey("Company_Id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TravelToBackend.Models.Company", b =>
                {
                    b.Navigation("Turebi");
                });
#pragma warning restore 612, 618
        }
    }
}
